server:
  port: 8080

hydra:
  oauth-public-url: http://localhost:4444
  oauth-private-url: http://localhost:4444
  admin-public-url: http://localhost:4445
  admin-private-url: http://localhost:4445

application:
  service-url: http://localhost:8081
  logout-url: ${hydra.oauth-public-url}/oauth2/sessions/logout

# For debugging purposes (not a good practice)
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
    reactive:
      max-chunk-size: 8192
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  security:
    oauth2:
      client:
        provider:
          hydra:
            authorization-uri: ${hydra.oauth-public-url}/oauth2/auth
            token-uri: ${hydra.oauth-private-url}/oauth2/token
            jwk-set-uri: ${hydra.oauth-private-url}/.well-known/jwks.json
            user-info-uri: ${hydra.oauth-private-url}/userinfo
            user-name-attribute: sub
        registration:
          hydra-openid:
            provider: hydra
            client-id: hydra-auth-code-client
            client-secret: hydra-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
            - openid
            - offline
            - profile.read
          hydra-code:
            provider: hydra
            client-id: hydra-auth-code-client
            client-secret: hydra-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
            - offline
            - profile.read
          hydra-service:
            provider: hydra
            client-id: hydra-service-client
            client-secret: hydra-secret
            authorization-grant-type: client_credentials
            scope:
            - offline
            - profile.read

# For sample github client id, see https://spring.io/guides/tutorials/spring-boot-oauth2/

#logging:
#  level:
#    org.springframework.security: TRACE

---
spring:
  profiles: docker-compose
  redis:
    host: redis

hydra:
  oauth-public-url: http://localhost:4444
  oauth-private-url: http://hydra:4444
  admin-public-url: http://localhost:4445
  admin-private-url: http://hydra:4445

application:
  service-url: http://learn-hydra-login-and-consent-ui:8081
