version: '3'

services:
  hydra:
    image: oryd/hydra:v1.3.2
    container_name: hydra
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://localhost:8081/login
      - URLS_CONSENT=http://localhost:8081/consent
      - URLS_LOGOUT=http://localhost:8081/signout
      - URLS_POST_LOGOUT_REDIRECT=http://localhost:8081/logout
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
    restart: unless-stopped

## Comment out below config if running apps for development in IDE

  learn-hydra-login-and-consent-ui:
    image: learn-hydra-login-and-consent-ui:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-ui
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8081:8081"

  learn-hydra-login-and-consent-oauth-client:
    image: learn-hydra-login-and-consent-oauth-client:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-oauth-client
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8080:8080"

  learn-hydra-login-and-consent-discovery-server:
    image: learn-hydra-login-and-consent-discovery-server:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-discovery-server
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8761:8761"

  learn-hydra-login-and-consent-gateway:
    image: learn-hydra-login-and-consent-gateway:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-gateway
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8888:8888"

  learn-hydra-login-and-consent-resource1:
    image: learn-hydra-login-and-consent-resource1:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-resource1
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8085:8085"

  learn-hydra-login-and-consent-resource2:
    image: learn-hydra-login-and-consent-resource2:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-resource2
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8086:8086"

  learn-hydra-login-and-consent-resource3:
    image: learn-hydra-login-and-consent-resource3:0.0.2-SNAPSHOT
    container_name: learn-hydra-login-and-consent-resource3
    environment:
       - "SPRING_PROFILES_ACTIVE=docker-compose" 
    ports:
      - "8087:8087"